version: "3.7"

services:
  
  namenode:
    image: jontavpess/hadoop-base:latest
    container_name: namenode
    hostname: namenode
    volumes:
      - ./input:/usr/input
      - ./user_data/hdfs/name:/usr/hadoop/dfs/name
    ports:
      - "8020:8020"
      - "8088:8088"
      - "9870:9870"
      - "50030:50030"
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1536m

  datanode:
    image: jontavpess/hadoop-base:latest
    container_name: datanode
    hostname: datanode
    volumes:
      - ./user_data/hdfs/data:/usr/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:8020"
    depends_on:
      - namenode
    ports:
      - "8021:8021"
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1536m

  jupyter-spark:
    image: jontavpess/jupyter-spark-base:latest
    container_name: jupyter-spark
    hostname: jupyter-spark
    volumes:
      - ./user_data/notebooks:/mnt/notebooks
      - ./input:/usr/input
    # env_file:
    #   - ./docker-images/jupyter-spark/config/jupyter-spark.env
    # environment:
    #   SPARK_MASTER: local[*]
    depends_on:
     - "namenode"
     - "datanode"
    ports:
      - 8888:8888
      - 4040:4040
      # - 4041:4041
      # - 4042:4042
      # - 4043:4043