version: "3.7"

services:
  
  namenode:
    image: jontavpess/hadoop-base:latest
    container_name: namenode
    hostname: namenode
    volumes:
      - ./input:/usr/input
      - ./user_data/hdfs/name:/usr/hadoop/dfs/name
    ports:
      - "8020:8020"
      - "9870:9870"
      - "50030:50030"
    deploy:
      resources:
        limits:
          memory: 3072m

  datanode:
    image: jontavpess/hadoop-base:latest
    container_name: datanode
    hostname: datanode
    volumes:
      - ./user_data/hdfs/data:/usr/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:8020"
    depends_on:
      - namenode
    ports:
      - "8021:8021"
    deploy:
      resources:
        limits:
          memory: 3072m

  jupyter-spark:
    image: jontavpess/jupyter-spark-base:latest
    container_name: jupyter-spark
    hostname: jupyter-spark
    volumes:
      - ./user_data/jupyter:/mnt/jupyter
      - ./input:/usr/input
    depends_on:
     - "namenode"
     - "datanode"
    ports:
      - 8888:8888
      - 9000:9000
      - 4040:4040
    deploy:
      resources:
        limits:
          memory: 3072m