version: "3.7"

services:
  
  namenode:
    image: jontavpess/hadoop-base:latest
    container_name: namenode
    hostname: namenode
    volumes:
      - ./input:/usr/input
      - ./user_data/hdfs/name:/usr/hadoop/dfs/name
    ports:
      - "8020:8020"
      - "8088:8088"
      - "9870:9870" 
      - "50030:50030" #inútil
    deploy:
      resources:
        limits:
          memory: 512m

  datanode-1:
    image: jontavpess/hadoop-base:latest
    container_name: datanode-1
    hostname: datanode-1
    volumes:
      - ./user_data/hdfs/data:/usr/hadoop/dfs/data
    ports:
      - "8042:8042"
    environment:
      SERVICE_PRECONDITION: "namenode:8020"
    depends_on:
      - namenode
    deploy:
      resources:
        limits:
          memory: 512m

  datanode-2:
    image: jontavpess/hadoop-base:latest
    container_name: datanode-2
    hostname: datanode-2
    volumes:
      - ./user_data/hdfs/data:/usr/hadoop/dfs/data
    ports:
      - "8043:8042"
    environment:
      SERVICE_PRECONDITION: "namenode:8020"
    depends_on:
      - namenode
    deploy:
      resources:
        limits:
          memory: 1024m

  jupyter-spark:
    image: jontavpess/jupyter-spark-base:latest
    container_name: jupyter-spark
    hostname: jupyter-spark
    volumes:
      - ./user_data/jupyter:/mnt/jupyter
      - ./input:/usr/input
    depends_on:
     - "namenode"
     - "datanode-1"
     - "datanode-2"
    ports:
      - 8888:8888
      - 9000:9000 #inútil
      - 4040:4040 #inútil
    deploy:
      resources:
        limits:
          memory: 512m